title = "The Rodeo"
baseURL = "https://jefe.io"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "UA-110468914-1"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Description and meta data for the search engines
  author = "eljefedelrodeodeljefe"
  description = "Writings and collections of Robert Jefe Lindstaedt."
  keywords = "blog,personal,coding"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = false
  algolia_appId     = ""
  algolia_apiKey    = ""
  algolia_indexName = ""

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Writings and collections of Robert Jefe Lindstaedt"

    # if you want to use gravatar for the header image
    gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "/images/avatar.png"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

  # social media profile urls for the footer links
  facebook   = ""
  twitter    = "https://twitter.com/eljefedelrodeo"
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/eljefedelrodeodeljefe"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
